Update package, URL, and copyright from Kortforsyningen to OSGeo
OSGeo/PROJ-JNI pull request #48
Opened 2021-08-22 16:39 UTC by willcohen

2021-08-22 19:47 UTC, desruisseaux commented
I did not tested yet, but at a first look it seems all right.

2021-08-23 05:33 UTC, kbevers commented
The code parts looks okay but you can't just change the copyright retroactively. Not sure if OSGeo is the correct copyright holder from now on either. I'll have to look into that and get back with better feedback.

2021-08-23 08:01 UTC, desruisseaux commented
Ah yes indeed, I was too focused on the code. Transfering the copyright may require Kortforsyningen to produce some legal paper, but doing such transfer is probably not needed. I think it is also fine to have code hosted at OSGeo with different copyright holders. It is the case of PROJ code itself if I remember right. It is also the standard practice at Apache Software Foundation for example.

2021-08-23 08:58 UTC, kbevers commented
There' are two problems here. The first is that "Kortforsyningen" is listed as a copyright holder in some places - that should be "Agency for Data Supply and Efficiency" (Kortforsyningen is a brandname within the agency and can't as such be a copyright holder). This should be corrected.
The second problem is that the copyright holder is overwritten here. That should be dealt with by adding new copyright lines for the years after 2019. So we have something like

> Copyright (c) Agency for Data Supply and Efficiency, 2019-2021
> Copyright (c) Open Source Geospatial Foundation, 2021-20xx

Still not sure if OSGeo is the proper copyright holder but at least it's better than nothing. Individual developers might also want to put their name in I guess.

2021-08-23 11:27 UTC, willcohen commented
Apologies. Will revise!

2021-08-23 11:41 UTC, kbevers commented
> Apologies

No worries, it's not easy to get these things right. After having done the copyright and license review of PROJ my spidey-sense is always tingling when it comes to meddling with the legalese

2021-09-14 16:26 UTC, willcohen commented
Apologies for losing track of this. Updated the statements to reflect a 2019-2021 and 2021 copyright, and force-pushed so that there's no incorrect labelling on an intermediate commit.

2021-09-14 16:53 UTC, desruisseaux commented
No problem, thanks for the update. Just tried and I confirm that it builds and passes the tests at least on my machine (not yet upgraded to PROJ 8). Opened a few random files and it seems all right. On a very minor note, some files have a trailing space on the following lines:

```
Copyright © 2019-2021 Agency for Data Supply and Efficiency
```

2021-09-14 18:08 UTC, willcohen commented
Good catch -- find/replace issue!

2021-09-15 06:00 UTC, kbevers requested changes

2021-09-15 14:49 UTC, willcohen commented on README.md
>  is temporary. The final name will be selected later.
Lines removed with 8cac538!

2021-09-16 05:05 UTC, kbevers approved these changes

2021-09-16 16:46 UTC, merged